src/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings
from students.views import index, view_404

urlpatterns = [
    path("admin/", admin.site.urls),
    path("students/", include("students.urls")),
    path("teachers/", include("teachers.urls")),
    path("groups/", include("groups.urls")),
    path("", index, name="index")
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = view_404

src/students/urls.py
from django.urls import path

from students.views import get_students, create_students, update_students, delete_students, summary_students

app_name = "students"

urlpatterns = [
    path("", get_students, name="get_students"),
    path("create/", create_students, name="create_students"),
    path("update/<int:pk>", update_students, name="update_students"),
    path("delete/<int:pk>", delete_students, name="delete_students"),
    path("summary-students/<int:pk>", summary_students, name="summary_students"),
]

src/students/models.py
import datetime


from django.core.validators import MinLengthValidator
from django.db import models
from faker import Faker


class Student(models.Model):
    avatar = models.ImageField(upload_to="media/", null=True, blank=True)
    first_name = models.CharField(max_length=120, validators=[MinLengthValidator(3)], null=True, blank=True)
    last_name = models.CharField(max_length=150, null=True, blank=True)
    email = models.EmailField(max_length=100)
    grade = models.PositiveIntegerField(default=0, null=True)
    birth_date = models.DateField(null=True, blank=True)
    summary = models.FileField(upload_to="files/", null=True, blank=True)
    group = models.ForeignKey("groups.Group", on_delete=models.CASCADE, default=13)

    @classmethod
    def generate_students(cls, count: int) -> None:
        faker = Faker()
        for i in range(count):
            student = Student(
                first_name=faker.first_name(),
                last_name=faker.last_name(),
                birth_date=faker.date_of_birth(minimum_age=18, maximum_age=70),
                email=faker.email(),
            )
            student.save()

    def age(self) -> int:
        return datetime.datetime.now().year - self.birth_date.year

    def __str__(self):
        return f"{self.first_name} {self.last_name}, {self.email}, {self.pk}"

src/students/forms.py
from django.forms import ModelForm
from students.models import Student


class StudentForm(ModelForm):
    class Meta:
        model = Student
        fields = [
            "avatar",
            "first_name",
            "last_name",
            "email",
            "group",
            "summary",
        ]

    @staticmethod
    def normalize_text(text):
        return text.strip().capitalize()

    def clean_first_name(self):
        return self.normalize_text(self.cleaned_data["first_name"])

    def clean_last_name(self):
        return self.normalize_text(self.cleaned_data["last_name"])

src/students/views.py
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from webargs import fields
from django.http import JsonResponse  # NOQA:F401
from django.shortcuts import render, get_object_or_404
from webargs.djangoparser import use_args
from django.db.models import Q

from students.forms import StudentForm
from students.models import Student
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect


def index(request: HttpRequest) -> HttpResponse:
    return render(request, template_name="index.html")


def view_404(request, exception):
    return render(request, template_name='404.html', status=404)


@use_args(
    {
        "first_name": fields.Str(
            required=False,
        ),
        "last_name": fields.Str(
            required=False,
        ),
        "search": fields.Str(
            required=False,
        ),
    },
    location="query",
)
def get_students(request: HttpRequest, params) -> HttpResponse:
    students = Student.objects.all()

    search_fields = ["first_name", "last_name", "email"]

    for param_name, param_value in params.items():
        if param_name == "search":
            or_filter = Q()
            for field in search_fields:
                or_filter |= Q(**{f"{field}__contains": param_value})
            students = students.filter(or_filter)
        else:
            students = students.filter(**{param_name: param_value})

    return render(request, template_name="students/get_students.html", context={"students": students})


@csrf_exempt
def create_students(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = StudentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("students:get_students"))
    elif request.method == "GET":
        form = StudentForm()

    return render(request, template_name="students/create_student.html", context={"form": form})


@csrf_exempt
def update_students(request: HttpRequest, pk: int) -> HttpResponse:
    student = get_object_or_404(Student.objects.all(), pk=pk)
    if request.method == "POST":
        form = StudentForm(request.POST, request.FILES, instance=student)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("students:get_students"))
    elif request.method == "GET":
        form = StudentForm(instance=student)

    return render(request, template_name="students/update_student.html", context={"form": form})


@csrf_exempt
def delete_students(request: HttpRequest, pk: int) -> HttpResponse:
    student = get_object_or_404(Student.objects.all(), pk=pk)

    if request.method == "POST":
        student.delete()
        return HttpResponseRedirect(reverse("students:get_students"))
    elif request.method == "GET":
        pass

    return render(request, template_name="students/delete_student.html", context={"student": student})


@csrf_exempt
def summary_students(request: HttpRequest, pk: int) -> HttpResponse:
    student = get_object_or_404(Student.objects.all(), pk=pk)
    return render(request, template_name="students/students_summary.html", context={"student": student})

src/templates/students/create_student.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <form method='post' style="width: 30em; margin: auto" enctype="multipart/form-data">
        {{ form|crispy }}
        <input type="submit" value="Create">
    </form>
{% endblock content %}

src/templates/students/delete_student.html
{% extends "index.html" %}
{% block content %}
    <form method='post'>
        <p>Are you sure you want to delete {{ student.first_name }} {{ student.last_name }}?</p>
        <input type="submit" value="Confirm">
    </form>

{% endblock content %}

src/templates/students/get_students.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block search %}
<form method="GET" action="{% url 'students:get_students' %}" style="margin-right: 80px;">

    <input type="text" name="search" placeholder="Search by name or email" style="
    background-color: #222;
    border-radius: 5px;
    color: #fff;
    border: solid 1px #fff;
    padding-left: 8px;">

    <button type="submit" style="
    background-color: #444;
    border: solid 1px #fff;
    border-radius: 5px;
    color: #fff;">Search</button>
</form>
{% endblock search %}


{% block content %}
<table class="table table-hover table-dark">
    <thead>
    <tr>
        <th scope="col">Avatar</th>
        <th scope="col">First name</th>
        <th scope="col">Last name</th>
        <th scope="col">Email</th>
        <th scope="col">Grade</th>
        <th scope="col">Birth date</th>
        <th scope="col">Age</th>
        <th scope="col">Group</th>
        <th scope="col">Summary</th>
        <th scope="col">Update</th>
        <th scope="col">Delete</th>
    </tr>
    </thead>
    {% for student in students %}
        <tbody>
        <tr>
            <td>
            {% if student.avatar %}
                <img src="{{ student.avatar.url }}" style="max-width: 70px; max-height: 70px;">
            {% else %}
                <span>No avatar</span>
            {% endif %}
            </td>
            <td>{{ student.first_name }}</td>
            <td>{{ student.last_name }}</td>
            <td>{{ student.email }}</td>
            <td>{{ student.grade }}</td>
            {% if student.birth_date %}
                <td>{{ student.birth_date }}</td>
                <td>{{ student.age }}</td>
            {% else %}
                <td>Unknown</td>
                <td>Unknown</td>
            {% endif %}
            <td>{{ student.group }}</td>
            <td>
                <a type="button" class="btn btn-info"
                   href="{% url "students:summary_students" student.pk %}">Summary</a>
            </td>
            <td>
                <a type="button" class="btn btn-info"
                   href="{% url "students:update_students" student.pk %}">Update</a>
            </td>
            <td>
                <a type="button" class="btn btn-danger"
                   href="{% url "students:delete_students" student.pk %}">Delete</a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock content %}

src/templates/students/students_summary.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    {% if student.summary %}
        <a href="{{ student.summary.url }}" class="btn btn-info">View Summary</a>
    {% else %}
        No Summary Available
    {% endif %}
{% endblock content %}

src/templates/students/update_student.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <form method='post', style="width: 30em; margin: auto" enctype="multipart/form-data">
        {{ form|crispy }}
        <input type="submit" class="btn btn-info" value="Update">
    </form>
{% endblock content %}