src/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings
from students.views import index, view_404

urlpatterns = [
    path("admin/", admin.site.urls),
    path("students/", include("students.urls")),
    path("teachers/", include("teachers.urls")),
    path("groups/", include("groups.urls")),
    path("", index, name="index")
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = view_404

src/teachers/urls.py
from django.urls import path

from teachers.views import get_teachers, create_teachers, update_teachers, delete_teachers, teacher_group

app_name = "teachers"

urlpatterns = [
    path("", get_teachers, name="get_teachers"),
    path("create/", create_teachers, name="create_teachers"),
    path("update/<int:pk>", update_teachers, name="update_teachers"),
    path("delete/<int:pk>", delete_teachers, name="delete_teachers"),
    path("teacher-groups/<int:pk>", teacher_group, name="teacher_group")
]

src/teachers/models.py
from datetime import datetime

from django.db import models
from faker import Faker


class Teacher(models.Model):
    avatar = models.ImageField(upload_to="media/", null=True, blank=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=100)
    birth_date = models.DateField(null=True, blank=True)
    email = models.EmailField(max_length=150)
    phone_number = models.CharField(max_length=30, null=True, blank=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    group = models.ManyToManyField("groups.Group")

    @classmethod
    def generate_teachers(cls, count: int) -> None:
        faker = Faker()
        for i in range(count):
            teacher = Teacher(
                first_name=faker.first_name(),
                last_name=faker.last_name(),
                birth_date=faker.date_of_birth(minimum_age=18, maximum_age=70),
                email=faker.email(),
                phone_number=faker.phone_number(),
                city=faker.city(),
            )
            teacher.save()

    def age(self) -> int:
        return datetime.now().year - self.birth_date.year

    def __str__(self):
        return f"{self.first_name} {self.last_name}, {self.phone_number}, {self.email}, {self.pk}"

src/teachers/forms.py
from django.forms import ModelForm
from teachers.models import Teacher


class TeacherForm(ModelForm):
    class Meta:
        model = Teacher
        fields = [
            "avatar",
            "first_name",
            "last_name",
            "email",
            "phone_number",
            "city",
            "birth_date",
            "group",
        ]

    @staticmethod
    def normalize_text(text):
        return text.strip().capitalize()

    def clean_first_name(self):
        return self.normalize_text(self.cleaned_data["first_name"])

    def clean_last_name(self):
        return self.normalize_text(self.cleaned_data["last_name"])

    def clean_city(self):
        return self.normalize_text(self.cleaned_data["city"])

src/teachers/views.py
from django.db.models import Q
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from webargs import fields
from webargs.djangoparser import use_args

from teachers.forms import TeacherForm
from teachers.models import Teacher


# Create your views here.
@use_args(
    {
        "first_name": fields.Str(
            required=False,
        ),
        "last_name": fields.Str(
            required=False,
        ),
        "search": fields.Str(
            required=False,
        ),
    },
    location="query",
)
def get_teachers(request: HttpRequest, params) -> HttpResponse:
    teachers = Teacher.objects.all()

    search_fields = [
        "first_name",
        "last_name",
        "email",
    ]

    for param_name, param_value in params.items():
        if param_name == "search":
            or_filter = Q()
            for field in search_fields:
                or_filter |= Q(**{f"{field}__contains": param_value})
            teachers = teachers.filter(or_filter)
        else:
            teachers = teachers.filter(**{param_name: param_value})
    return render(request, template_name="teachers/get_teachers.html", context={"teachers": teachers})


@csrf_exempt
def create_teachers(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = TeacherForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("teachers:get_teachers"))
    elif request.method == "GET":
        form = TeacherForm()

    return render(request, template_name="teachers/create_teachers.html", context={"form": form})


@csrf_exempt
def update_teachers(request: HttpRequest, pk: int) -> HttpResponse:
    teacher = get_object_or_404(Teacher.objects.all(), pk=pk)
    if request.method == "POST":
        form = TeacherForm(request.POST, request.FILES, instance=teacher)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("teachers:get_teachers"))
    elif request.method == "GET":
        form = TeacherForm(instance=teacher)

    return render(request, template_name="teachers/update_teachers.html", context={"form": form})


@csrf_exempt
def delete_teachers(request: HttpRequest, pk: int) -> HttpResponse:
    teacher = get_object_or_404(Teacher.objects.all(), pk=pk)
    if request.method == "POST":
        teacher.delete()
        return HttpResponseRedirect(reverse("teachers:get_teachers"))
    elif request.method == "GET":
        pass

    return render(request, template_name="teachers/delete_teachers.html", context={"teacher": teacher})


@csrf_exempt
def teacher_group(request: HttpRequest, pk: int) -> HttpResponse:
    teacher = get_object_or_404(Teacher.objects.all(), pk=pk)
    groups = teacher.group.all()

    return render(request, template_name="teachers/teachers_group.html", context={
        "teacher": teacher, "groups": groups}, )

src/templates/teachers/create_teachers.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <form method='post' style="width: 30em; margin: auto" enctype="multipart/form-data">
        {{ form|crispy }}
        <input type="submit" value="Create">
    </form>
{% endblock content %}

src/templates/teachers/delete_teachers.html
{% extends "index.html" %}
{% block content %}
    <form method='post'>
        <p>Are you sure you want to delete {{ teacher.first_name }} {{ teacher.last_name }}?</p>
        <input type="submit" class="btn btn-danger" value="Confirm">
    </form>

{% endblock content %}

src/templates/teachers/get_teachers.html
{% extends "index.html" %}
{% load crispy_forms_tags %}




{% block content %}
<table class="table table-hover table-dark">
    <thead>
    <tr>
        <th scope="col">Avatar</th>
        <th scope="col">First name</th>
        <th scope="col">Last name</th>
        <th scope="col">Email</th>
        <th scope="col">Phone number</th>
        <th scope="col">City</th>
        <th scope="col">Birth date</th>
        <th scope="col">Age</th>
        <th scope="col">Update</th>
        <th scope="col">Delete</th>
        <th scope="col">Groups</th>
    </tr>
    </thead>
    {% for teacher in teachers %}
        <tbody>
        <tr>
             <td>
            {% if teacher.avatar %}
                <img src="{{ teacher.avatar.url }}"  style="max-width: 70px; max-height: 70px;">
            {% else %}
                <span>No avatar</span>
            {% endif %}
            </td>
            <td>{{ teacher.first_name }}</td>
            <td>{{ teacher.last_name }}</td>
            <td>{{ teacher.email }}</td>
            <td>{{ teacher.phone_number|default:"Unknown"}}</td>
            <td>{{ teacher.city|default:"Unknown"}}</td>
            {% if teacher.birth_date %}
                <td>{{ teacher.birth_date }}</td>
                <td>{{ teacher.age }}</td>
            {% else %}
                <td>Unknown</td>
                <td>Unknown</td>
            {% endif %}
            <td>
                <a type="button" class="btn btn-info"
                   href="{% url "teachers:update_teachers" teacher.pk %}">Update</a>
            </td>
            <td>
                <a type="button" class="btn btn-danger"
                   href="{% url "teachers:delete_teachers" teacher.pk %}">Delete</a>
            </td>
             <td>
                <a type="button" class="btn btn-info"
                   href="{% url "teachers:teacher_group" teacher.pk %}">Groups</a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock content %}

src/templates/teachers/teachers_group.html
{% extends "index.html" %}




{% block content %}
<h1>Groups {{ teacher.first_name }} {{ teacher.last_name }}</h1>
<table class="table table-hover table-dark">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Start date</th>
        <th scope="col">Max quantity students</th>
        <th scope="col">Max quantity teachers</th>
        <th scope="col">Status</th>
        <th scope="col">Duration study months</th>
    </tr>
    </thead>
    {% for group in groups %}
        <tbody>
        <tr>
            <th scope="row"> {{ group.pk }}</th>
            <td>{{ group.name }}</td>
            <td>{{ group.start_date|default:"Unknown"}}</td>
            <td>{{ group.max_quantity_students }}</td>
            <td>{{ group.max_quantity_teachers }}</td>
            <td>{{ group.status }}</td>
            <td>{{ group.duration_study_months }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock content %}

src/templates/teachers/update_teachers.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <form method='post', style="width: 30em; margin: auto" enctype="multipart/form-data">
        {{ form|crispy }}
        <input type="submit" class="btn btn-info" value="Update">
    </form>
{% endblock content %}