src/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings
from students.views import index, view_404

urlpatterns = [
    path("admin/", admin.site.urls),
    path("students/", include("students.urls")),
    path("teachers/", include("teachers.urls")),
    path("groups/", include("groups.urls")),
    path("", index, name="index")
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = view_404

src/groups/urls.py
from django.urls import path

from groups.views import get_groups, create_groups, update_groups, delete_groups

app_name = "groups"

urlpatterns = [
    path("", get_groups, name="get_groups"),
    path("create/", create_groups, name="create_groups"),
    path("update/<int:pk>", update_groups, name="update_groups"),
    path("delete/<int:pk>", delete_groups, name="delete_groups"),
]

src/groups/models.py
import random

from django.core.validators import MaxValueValidator
from django.db import models
from faker import Faker


class Group(models.Model):
    STATUS_GROUP = [
        ("Active", "active"),
        ("Completed", "completed"),
        ("Suspended", "suspended"),
    ]
    GROUP_NAME = [
        ("Python", "Python"),
        ("Java", "Java"),
        ("Frontend", "Frontend"),
        ("C++", "C++"),
        ("Php", "Php"),
        ("C#", "C#"),
    ]

    start_date = models.DateField(null=True, blank=True)
    max_quantity_students = models.PositiveIntegerField(default=1, validators=[MaxValueValidator(20)])
    name = models.CharField(max_length=100, choices=GROUP_NAME, default=GROUP_NAME[0])
    max_quantity_teachers = models.PositiveIntegerField(default=1)
    status = models.CharField(max_length=20, choices=STATUS_GROUP, default="active")
    duration_study_months = models.PositiveIntegerField(default=1, validators=[MaxValueValidator(24)])

    @classmethod
    def generate_groups(cls, count: int) -> None:
        faker = Faker()
        for i in range(count):
            group = Group(
                start_date=faker.date(start_date="2021-01-01", end_date="2024-12-31"),
                quantity_students=faker.random_int(min_value=1, max_value=20),
                quantity_teachers=faker.random_int(min_value=1, max_value=3),
                name=random.choice([name[0] for name in cls.GROUP_NAME]),
                status=random.choice([status[0] for status in cls.STATUS_GROUP]),
                duration_study_months=faker.random_int(min_value=1, max_value=18),
            )
            group.save()

    def __str__(self):
        return (
            f"({self.pk}) {self.name}, {self.max_quantity_students} students, {self.start_date},"
            f"{self.duration_study_months} months, {self.max_quantity_teachers}"
        )

src/groups/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from groups.models import Group


class GroupForm(ModelForm):
    class Meta:
        model = Group
        fields = [
            "name",
            "start_date",
            "max_quantity_teachers",
            "duration_study_months",
            "max_quantity_students",
            "status",
        ]

    @staticmethod
    def normalize_text(text):
        return text.strip().capitalize()

    def clean_name(self):
        return self.normalize_text(self.cleaned_data["name"])

    def clean_status(self):
        return self.normalize_text(self.cleaned_data["status"])

    def clean_start_date(self):
        start_date = self.cleaned_data["start_date"]
        if start_date is None:
            raise ValidationError("Enter a date")
        return start_date

src/groups/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from groups.forms import GroupForm
from django.views.decorators.csrf import csrf_exempt
from webargs import fields
from webargs.djangoparser import use_args
from django.db.models import Q
from groups.models import Group
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect


@use_args(
    {
        "name": fields.Str(
            required=False,
        ),
        "status": fields.Str(
            required=False,
        ),
        "duration_study_months": fields.Int(required=False),
        "start_date": fields.Int(required=False),
        "search": fields.Str(
            required=False,
        ),
    },
    location="query",
)
def get_groups(request: HttpRequest, params) -> HttpResponse:
    groups = Group.objects.all()
    search_fields = ["name", "duration_study_months", "status", "start_date"]
    for param_name, param_value in params.items():
        if param_name == "search":
            or_filter = Q()
            for field in search_fields:
                or_filter |= Q(**{f"{field}__contains": param_value})
            groups = groups.filter(or_filter)
        else:
            groups = groups.filter(**{param_name: param_value})

    return render(request, template_name="groups/get_groups.html", context={"groups": groups})


@csrf_exempt
def create_groups(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/groups")
    elif request.method == "GET":
        form = GroupForm()

    return render(request, template_name="groups/create_group.html", context={"form": form})


@csrf_exempt
def update_groups(request: HttpRequest, pk: int) -> HttpResponse:
    group = get_object_or_404(Group.objects.all(), pk=pk)
    if request.method == "POST":
        form = GroupForm(request.POST, instance=group)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("groups:get_groups"))
    elif request.method == "GET":
        form = GroupForm(instance=group)

    return render(request, template_name="groups/update_groups.html", context={"form": form})


@csrf_exempt
def delete_groups(request: HttpRequest, pk: int) -> HttpResponse:
    group = get_object_or_404(Group.objects.all(), pk=pk)

    if request.method == "POST":
        group.delete()
        return HttpResponseRedirect(reverse("groups:get_groups"))
    elif request.method == "GET":
        pass

    return render(request, template_name="groups/delete_groups.html", context={"group": group})

src/templates/groups/create_group.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <form method='post', style="width: 30em; margin: auto">
        {{ form|crispy }}
        <input type="submit" value="Create">
    </form>
{% endblock content %}

src/templates/groups/delete_groups.html
{% extends "index.html" %}
{% block content %}
    <form method='post'>
        <p>Are you sure you want to
            delete {{ group.name }}, {{ group.start_date }}, {{ group.status }}?</p>
        <input type="submit" class="btn btn-danger" value="Confirm">
    </form>

{% endblock content %}

src/templates/groups/get_groups.html
{% extends "index.html" %}
{% load crispy_forms_tags %}




{% block content %}
<table class="table table-hover table-dark">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Start date</th>
        <th scope="col"> Max quantity students</th>
        <th scope="col">Max quantity teachers</th>
        <th scope="col">Status</th>
        <th scope="col">Duration study months</th>
        <th scope="col">Update</th>
        <th scope="col">Delete</th>
    </tr>
    </thead>
    {% for group in groups %}
        <tbody>
        <tr>
            <th scope="row"> {{ group.pk }}</th>
            <td>{{ group.name }}</td>
            <td>{{ group.start_date|default:"Unknown" }}</td>
            <td>{{ group.max_quantity_students }}</td>
            <td>{{ group.max_quantity_teachers}}</td>
            <td>{{ group.status }}</td>
            <td>{{ group.duration_study_months}}</td>

            <td>
                <a type="button" class="btn btn-info"
                   href="{% url "groups:update_groups" group.pk %}">Update</a>
            </td>
            <td>
                <a type="button" class="btn btn-danger"
                   href="{% url "groups:delete_groups" group.pk %}">Delete</a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock content %}

src/templates/groups/update_groups.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <form method='post', style="width: 30em; margin: auto">
        {{ form|crispy }}
        <input type="submit" class="btn btn-info" value="Update">
    </form>
{% endblock content %}